#Login panel
user = User:
password = Password:
login = Login
unregistered = Continue without login
signIn = Sign in
loginError = Both fields must be filled!

#NewPartyPanel
welcome = Welcome
guest = guest
howManyPeople = How many people do you want to invite?
next = Next
cancel = Cancel
guest = Guest

#Hiring panel
organizingFor = Organizing a party for
people = people
filterBy = Filter by:
selectType = Select type:
drinks = Bebidas
food = Comidas
spaces = Espacios
decoration = Decoracion
others = Otros
continue = Continuar

#Register panel
register = Register
goBack = Go back

#Product panel
add = Add

#Shopping cart
shoppingCart = Shopping cart
products = products
removeAll =  Delete all
undo = Undo
continueHiring = Continue hiring
total = Total
productDetails = Product details
quantity = Quantity
priceUnit = Price/Unit
remove = Remove

#OrderConfirmation panel
orderConfirmation = Order confirmation
name = Name
surname = Surname
dni = DNI/NIF
date = Date
getDate = Select date from the system
comments = Comments
reviewCart = Review your cart
addYourData = Add your data
addComment = Add a comment to your order
confirmOrder = Confirm
pay = Pay
infoMissingTitle = PartyManager: Error -  missing fields
infoMissing = You must fill every field in order to pay

#Success panel
success = Success!
orderProcesed = Your order has been processed!
newParty = New party
printReceipt = Print receipt
printing = Printing receipt...
printingTitle = PartyManager: Print receipt

# Menu bar
languages = Languages
english = English
spanish = Spanish
help = Help
about = About
new = New
cancel = Cancel
exit = Exit
party = Party
exitConfirmation = Are you sure you want to exit the application? All your changes will be lost

# About dialog
aboutTitle = Party Manager: About
aboutMessage = Party Manager\nDeveloped by Carlos Manrique Ener\nDeveloped by Carlos Manrique Enguita\nUO258425\Version v1.0.0